pipelines: add initial builds
crossplane/templating-controller pull request #9
Opened 2020-02-22 02:08 UTC by suskin

This adds a set of pipeline builds with the same names as the template
stack pattern we've been using. Some of the pipelines are even using the
same code.

## Testing

* The shared pipelines have been tested by other projects
* I have not tested the specifics of the project-specific pipelines yet

## Other work

* [ ] Create jobs in Jenkins by copying them from a template stack and changing the repository urls
* [ ] Add a webhook to the github project settings
* [ ] Document the release process

2020-03-10 11:08 UTC, muvaf requested changes

2020-03-10 11:08 UTC, muvaf commented on Jenkinsfile.tag
> +runStackTagPipeline()
I don't think we should re-use stack pipelines in this repo as it's not a stack.

2020-03-18 09:00 UTC, muvaf commented
@suskin would you like to update `Jenkinsfile.branch` and `Jenkinsfile.tag` files to not depend on the stack publishing pipelines?

2020-03-19 00:25 UTC, suskin commented
Since we're no longer planning on using the stack tooling, I'll close this PR and we can open a different one with the changes which follow the approach we want to take.

2020-03-19 00:25 UTC, closed without merging